name: 'Hello world'
description: 'Greet someone and record the time'
inputs: #'input' parameters are stored as environment variables on the CI server/runner.
  who-to-greet: #id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs: #'outputs' which are what's going to be output from stdout and that'll show up in the build log.
  time: #id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}